{{- if .Values.backend.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datahub.backendFullname" . }}
  labels:
    app: {{ include "datahub.backendName" . }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.backend.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
