{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datahub.frontendFullname" . }}
  labels:
    app: {{ include "datahub.frontendName" . }}
data:
  {{- range $key, $value := .Values.frontend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
